In [1]:
import numpy as np


In [3]:
rev_q1 = np.array([10,12,9])
rev_q1.ndim

1

In [4]:
rev = np.array([[10,12,9],[12,15,7]])
rev.ndim


2

In [6]:
rev

array([[10, 12,  9],
       [12, 15,  7]])

In [7]:
rev.size


6

In [9]:
rev.shape

(2, 3)

In [10]:
np.sort(rev)

array([[ 9, 10, 12],
       [ 7, 12, 15]])

In [11]:
rev.flatten()

array([10, 12,  9, 12, 15,  7])

In [13]:
rev.min()

np.int64(7)

In [14]:
rev.max()

np.int64(15)