In [1]:
import numpy as np

In [2]:
a = np.array([
    [10,  0, -2],
    [ 5,  8,  4],
    [-3,  1,  7]
])
b = np.array([
    [10,  0, -2],
    [ 5,  8,  4],
    [-3,  1,  7]
])

In [3]:
a+b

array([[20,  0, -4],
       [10, 16,  8],
       [-6,  2, 14]])

In [5]:
b-a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
c = np.array([1,2,3])
d = np.array([4,5,6])

np.cross(c,d)

array([-3,  6, -3])

In [7]:
features = np.array([
    [2000,3],
    [1800,2]
])
weights = np.array([150,50000])
np.dot(features,weights)

array([450000, 370000])