In [1]:
import numpy as np

In [2]:
a = np.array([3,6,7,8])


In [3]:
a[0:2]

array([3, 6])

In [5]:
a[2:]

array([7, 8])

In [6]:
a[-1]

np.int64(8)

In [7]:
a[-2:]

array([7, 8])

In [8]:
b = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])

In [10]:
print(b[1,2])

6


In [11]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])

# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [12]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [13]:
e = np.array([
    [104 , 'Venkat'],
    [105 , 'jhony'],
    [106 , 'kartik'],
])
e

array([['104', 'Venkat'],
       ['105', 'jhony'],
       ['106', 'kartik']], dtype='<U21')

In [14]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'jhony'],
       ['106', 'kartik']], dtype='<U21')