In [12]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x, y = make_classification(
    n_features=10, 
    n_samples=1000, 
    n_informative=4,
    n_redundant=6,
    n_repeated=0,
    n_classes=2, 
    random_state=42
)

# Split data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

Method 1 : Evaluate the Model Using train test split and tune parameters by trial and error

In [13]:
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

model = DecisionTreeClassifier(criterion='gini',max_depth=5)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
report = classification_report(y_test,y_pred)

print(report)


              precision    recall  f1-score   support

           0       0.83      0.93      0.88       122
           1       0.93      0.81      0.87       128

    accuracy                           0.87       250
   macro avg       0.88      0.87      0.87       250
weighted avg       0.88      0.87      0.87       250



# Method 2 : Cross Validation Score

In [14]:
from sklearn.model_selection import cross_val_score
cross_val_score(DecisionTreeClassifier(criterion='gini',max_depth=10),x,y,cv=5)

array([0.845, 0.865, 0.88 , 0.9  , 0.89 ])

In [15]:
from sklearn.model_selection import cross_val_score
cross_val_score(DecisionTreeClassifier(criterion='gini',max_depth=10),x,y,cv=5)

array([0.85 , 0.87 , 0.855, 0.89 , 0.89 ])

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(DecisionTreeClassifier(criterion='gini',max_depth=10),x,y,cv=5)

array([0.875, 0.88 , 0.87 , 0.895, 0.91 ])

In [22]:
critterion = ['gini','entropy']
max_depth = [5,10,15]

avg_score= {}

for c in critterion:
    for d in max_depth:
        clf = DecisionTreeClassifier(criterion=c , max_depth= d)
        score_list = cross_val_score(clf,x,y,cv =10)
        avg_score[c+"_"+str(d)]+np.average(score_list)

avg_score

KeyError: 'gini_5'